
import EnumValue = require('dw/value/EnumValue')
import MarkupText = require('dw/content/MarkupText');
import MediaFile = require('dw/content/MediaFile');

// autogeneratedfile - 'c:\Users\fonsc\OneDrive\Escritorio\capa_brayan\data_impex\capa_brayan\meta\system-objecttype-extensions.xml'
declare global {
    module ICustomAttributes {

		interface OrderAddress {
			/**
			* Email
			* 
			* @source [attribute](file:c:\Users\fonsc\OneDrive\Escritorio\capa_brayan\data_impex\capa_brayan\meta\system-objecttype-extensions.xml#5) 
			*/
			emailAddress: string | null;

		}
		interface Profile {
			/**
			* First Purchase
			* 
			* @source [attribute](file:c:\Users\fonsc\OneDrive\Escritorio\capa_brayan\data_impex\capa_brayan\meta\system-objecttype-extensions.xml#17) 
			*/
			first_purchase: boolean | null;

		}
		interface CustomerAddress {
			/**
			* Email Address
			* 
			* @source [attribute](file:c:\Users\fonsc\OneDrive\Escritorio\capa_brayan\data_impex\capa_brayan\meta\system-objecttype-extensions.xml#29) 
			*/
			emailAddress: string | null;

			/**
			* First Purchase
			* 
			* @source [attribute](file:c:\Users\fonsc\OneDrive\Escritorio\capa_brayan\data_impex\capa_brayan\meta\system-objecttype-extensions.xml#36) 
			*/
			first_purchase: boolean | null;

		}
	}
}

declare global {
	interface IGetCustomPreferenceValue {
		
	}
}